apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: devuser
            - name: POSTGRES_PASSWORD
              value: devpass123
            - name: POSTGRES_DB
              value: devdb
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

